class Node:
	def __init__(self,data):
		self.data= data
		self.next= None
	def getNext(self):
		return self.next
	def getData(self):
		return self.data
	def setNext(self,next):
		self.next= next
	def setData(self,data):
		self.data= data